apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: jhipster
  labels:
    app: store
spec:
  selector:
    app: store
  type: LoadBalancer
  externalIPs:
  - 10.66.12.129
  ports:
    - name: http
      port: 8080
